project:
  type: website
  output-dir: docs

website:
  title: "Saikat Kumar Dey"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/saikatkumardey
      - icon: twitter
        href: https://x.com/saikatkrdey
format:
  html:
    theme: simplex
    css: styles.css

execute:
  freeze: auto

resources:
  - CNAME
